# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JuliaInterpreter]]
deps = ["InteractiveUtils"]
git-tree-sha1 = "351096eba0dff5ae69a6cc318f737a6e60c89aac"
repo-rev = "master"
repo-url = "https://github.com/JuliaDebug/JuliaInterpreter.jl"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.1.1"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
