name = "Debugger"
uuid = "377c9342-27ac-11e9-0cf7-e3c6726642c6"
authors = ["Kristoffer Carlsson <kcarlsson89@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
